version: '3.8'

services:

    mailbee:
        image: node:16
        container_name: mailbee
        user: "node"
        working_dir: /mailbee
        ports:
            - 3000:3000
        environment:
            - NODE_ENV=dev
        volumes:
            - ./src:/mailbee
            - ./config.yml:/mailbee/config.yml
            - ./template.html:/mailbee/template.html
        command: "npm run-script dev"