version: '3.8'

services:

    redis: # required
        image: redis:7
        container_name: redis_mailbee

    mailbee: # required
        image: ctrlouis/mailbee
        container_name: mailbee
        ports:
            - 3000:3000
        volumes:
            - ./config.yml:/mailbee/config.yml
            - ./template.html:/mailbee/template.html
        links:
            - redis
        depends_on:
            - redis

    prometheus: # optionnal (for metrics)
        image: prom/prometheus:latest
        container_name: prometheus_mailbee
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        links:
            - mailbee
        depends_on:
            - mailbee
    
    grafana: # optionnal (for metrics)
        image: grafana/grafana:latest
        container_name: grafana_mailbee
        ports:
            - 9090:3000
        environment:
            - GF_AUTH_DISABLE_LOGIN_FORM=true
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        volumes:
            - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
            - ./dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
            - ./dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
        links:
            - prometheus
        depends_on:
            - prometheus